# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xviz/v2/annotation.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from xviz_avs.v2 import options_pb2 as xviz_dot_v2_dot_options__pb2
from xviz_avs.v2 import style_pb2 as xviz_dot_v2_dot_style__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18xviz/v2/annotation.proto\x12\x07xviz.v2\x1a\x15xviz/v2/options.proto\x1a\x13xviz/v2/style.proto\"9\n\nVisualBase\x12\x11\n\tobject_id\x18\x01 \x01(\t:\x18\xc2\xbb\x1a\x14\x63ore/annotation_base\"\x8f\x01\n\x06Visual\x12!\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32\x13.xviz.v2.VisualBase\x12\x15\n\rstyle_classes\x18\x02 \x03(\t\x12/\n\x0cinline_style\x18\x03 \x01(\x0b\x32\x19.xviz.v2.StyleObjectValue:\x1a\xc2\xbb\x1a\x16\x63ore/annotation_visualBA\n\x0b\x63om.xviz.v2B\x0f\x41nnotationProtoP\x01Z\x04v2pb\xa2\x02\x04XVIZ\xaa\x02\x07xviz.V2\xca\x02\x07Xviz\\V2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xviz.v2.annotation_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.xviz.v2B\017AnnotationProtoP\001Z\004v2pb\242\002\004XVIZ\252\002\007xviz.V2\312\002\007Xviz\\V2'
  _globals['_VISUALBASE']._options = None
  _globals['_VISUALBASE']._serialized_options = b'\302\273\032\024core/annotation_base'
  _globals['_VISUAL']._options = None
  _globals['_VISUAL']._serialized_options = b'\302\273\032\026core/annotation_visual'
  _globals['_VISUALBASE']._serialized_start=81
  _globals['_VISUALBASE']._serialized_end=138
  _globals['_VISUAL']._serialized_start=141
  _globals['_VISUAL']._serialized_end=284
# @@protoc_insertion_point(module_scope)
