# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xviz/v2/primitives.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from xviz_avs.v2 import options_pb2 as xviz_dot_v2_dot_options__pb2
from xviz_avs.v2 import style_pb2 as xviz_dot_v2_dot_style__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='xviz/v2/primitives.proto',
  package='xviz.v2',
  syntax='proto3',
  serialized_options=_b('\n\013com.xviz.v2B\017PrimitivesProtoP\001Z\004v2pb\242\002\004XVIZ\252\002\007xviz.V2\312\002\007Xviz\\V2'),
  serialized_pb=_b('\n\x18xviz/v2/primitives.proto\x12\x07xviz.v2\x1a\x15xviz/v2/options.proto\x1a\x13xviz/v2/style.proto\"]\n\rPrimitiveBase\x12\x11\n\tobject_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63lasses\x18\x02 \x03(\t\x12(\n\x05style\x18\x03 \x01(\x0b\x32\x19.xviz.v2.StyleObjectValue\"e\n\x06\x43ircle\x12$\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32\x16.xviz.v2.PrimitiveBase\x12\x0e\n\x06\x63\x65nter\x18\x02 \x03(\x02\x12\x0e\n\x06radius\x18\x03 \x01(\x02:\x15\xc2\xbb\x1a\x11primitives/circle\"\x88\x01\n\x05Image\x12$\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32\x16.xviz.v2.PrimitiveBase\x12\x10\n\x08position\x18\x02 \x03(\x02\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\x10\n\x08width_px\x18\x04 \x01(\r\x12\x11\n\theight_px\x18\x05 \x01(\r:\x14\xc2\xbb\x1a\x10primitives/image\"c\n\x05Point\x12$\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32\x16.xviz.v2.PrimitiveBase\x12\x0e\n\x06points\x18\x02 \x03(\x02\x12\x0e\n\x06\x63olors\x18\x03 \x01(\x0c:\x14\xc2\xbb\x1a\x10primitives/point\"Y\n\x07Polygon\x12$\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32\x16.xviz.v2.PrimitiveBase\x12\x10\n\x08vertices\x18\x02 \x03(\x02:\x16\xc2\xbb\x1a\x12primitives/polygon\"k\n\x08Polyline\x12$\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32\x16.xviz.v2.PrimitiveBase\x12\x10\n\x08vertices\x18\x02 \x03(\x02\x12\x0e\n\x06\x63olors\x18\x03 \x01(\x0c:\x17\xc2\xbb\x1a\x13primitives/polyline\"s\n\x07Stadium\x12$\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32\x16.xviz.v2.PrimitiveBase\x12\r\n\x05start\x18\x02 \x03(\x02\x12\x0b\n\x03\x65nd\x18\x03 \x03(\x02\x12\x0e\n\x06radius\x18\x04 \x01(\x02:\x16\xc2\xbb\x1a\x12primitives/stadium\"a\n\x04Text\x12$\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32\x16.xviz.v2.PrimitiveBase\x12\x10\n\x08position\x18\x02 \x03(\x02\x12\x0c\n\x04text\x18\x03 \x01(\t:\x13\xc2\xbb\x1a\x0fprimitives/textBA\n\x0b\x63om.xviz.v2B\x0fPrimitivesProtoP\x01Z\x04v2pb\xa2\x02\x04XVIZ\xaa\x02\x07xviz.V2\xca\x02\x07Xviz\\V2b\x06proto3')
  ,
  dependencies=[xviz_dot_v2_dot_options__pb2.DESCRIPTOR,xviz_dot_v2_dot_style__pb2.DESCRIPTOR,])




_PRIMITIVEBASE = _descriptor.Descriptor(
  name='PrimitiveBase',
  full_name='xviz.v2.PrimitiveBase',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='object_id', full_name='xviz.v2.PrimitiveBase.object_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='classes', full_name='xviz.v2.PrimitiveBase.classes', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='style', full_name='xviz.v2.PrimitiveBase.style', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=174,
)


_CIRCLE = _descriptor.Descriptor(
  name='Circle',
  full_name='xviz.v2.Circle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='base', full_name='xviz.v2.Circle.base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='center', full_name='xviz.v2.Circle.center', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='radius', full_name='xviz.v2.Circle.radius', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\302\273\032\021primitives/circle'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=277,
)


_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='xviz.v2.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='base', full_name='xviz.v2.Image.base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position', full_name='xviz.v2.Image.position', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='xviz.v2.Image.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width_px', full_name='xviz.v2.Image.width_px', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height_px', full_name='xviz.v2.Image.height_px', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\302\273\032\020primitives/image'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=280,
  serialized_end=416,
)


_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='xviz.v2.Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='base', full_name='xviz.v2.Point.base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='points', full_name='xviz.v2.Point.points', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='colors', full_name='xviz.v2.Point.colors', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\302\273\032\020primitives/point'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=418,
  serialized_end=517,
)


_POLYGON = _descriptor.Descriptor(
  name='Polygon',
  full_name='xviz.v2.Polygon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='base', full_name='xviz.v2.Polygon.base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vertices', full_name='xviz.v2.Polygon.vertices', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\302\273\032\022primitives/polygon'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=519,
  serialized_end=608,
)


_POLYLINE = _descriptor.Descriptor(
  name='Polyline',
  full_name='xviz.v2.Polyline',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='base', full_name='xviz.v2.Polyline.base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vertices', full_name='xviz.v2.Polyline.vertices', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='colors', full_name='xviz.v2.Polyline.colors', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\302\273\032\023primitives/polyline'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=610,
  serialized_end=717,
)


_STADIUM = _descriptor.Descriptor(
  name='Stadium',
  full_name='xviz.v2.Stadium',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='base', full_name='xviz.v2.Stadium.base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start', full_name='xviz.v2.Stadium.start', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='xviz.v2.Stadium.end', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='radius', full_name='xviz.v2.Stadium.radius', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\302\273\032\022primitives/stadium'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=719,
  serialized_end=834,
)


_TEXT = _descriptor.Descriptor(
  name='Text',
  full_name='xviz.v2.Text',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='base', full_name='xviz.v2.Text.base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position', full_name='xviz.v2.Text.position', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='xviz.v2.Text.text', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\302\273\032\017primitives/text'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=836,
  serialized_end=933,
)

_PRIMITIVEBASE.fields_by_name['style'].message_type = xviz_dot_v2_dot_style__pb2._STYLEOBJECTVALUE
_CIRCLE.fields_by_name['base'].message_type = _PRIMITIVEBASE
_IMAGE.fields_by_name['base'].message_type = _PRIMITIVEBASE
_POINT.fields_by_name['base'].message_type = _PRIMITIVEBASE
_POLYGON.fields_by_name['base'].message_type = _PRIMITIVEBASE
_POLYLINE.fields_by_name['base'].message_type = _PRIMITIVEBASE
_STADIUM.fields_by_name['base'].message_type = _PRIMITIVEBASE
_TEXT.fields_by_name['base'].message_type = _PRIMITIVEBASE
DESCRIPTOR.message_types_by_name['PrimitiveBase'] = _PRIMITIVEBASE
DESCRIPTOR.message_types_by_name['Circle'] = _CIRCLE
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
DESCRIPTOR.message_types_by_name['Point'] = _POINT
DESCRIPTOR.message_types_by_name['Polygon'] = _POLYGON
DESCRIPTOR.message_types_by_name['Polyline'] = _POLYLINE
DESCRIPTOR.message_types_by_name['Stadium'] = _STADIUM
DESCRIPTOR.message_types_by_name['Text'] = _TEXT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PrimitiveBase = _reflection.GeneratedProtocolMessageType('PrimitiveBase', (_message.Message,), {
  'DESCRIPTOR' : _PRIMITIVEBASE,
  '__module__' : 'xviz.v2.primitives_pb2'
  # @@protoc_insertion_point(class_scope:xviz.v2.PrimitiveBase)
  })
_sym_db.RegisterMessage(PrimitiveBase)

Circle = _reflection.GeneratedProtocolMessageType('Circle', (_message.Message,), {
  'DESCRIPTOR' : _CIRCLE,
  '__module__' : 'xviz.v2.primitives_pb2'
  # @@protoc_insertion_point(class_scope:xviz.v2.Circle)
  })
_sym_db.RegisterMessage(Circle)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'xviz.v2.primitives_pb2'
  # @@protoc_insertion_point(class_scope:xviz.v2.Image)
  })
_sym_db.RegisterMessage(Image)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), {
  'DESCRIPTOR' : _POINT,
  '__module__' : 'xviz.v2.primitives_pb2'
  # @@protoc_insertion_point(class_scope:xviz.v2.Point)
  })
_sym_db.RegisterMessage(Point)

Polygon = _reflection.GeneratedProtocolMessageType('Polygon', (_message.Message,), {
  'DESCRIPTOR' : _POLYGON,
  '__module__' : 'xviz.v2.primitives_pb2'
  # @@protoc_insertion_point(class_scope:xviz.v2.Polygon)
  })
_sym_db.RegisterMessage(Polygon)

Polyline = _reflection.GeneratedProtocolMessageType('Polyline', (_message.Message,), {
  'DESCRIPTOR' : _POLYLINE,
  '__module__' : 'xviz.v2.primitives_pb2'
  # @@protoc_insertion_point(class_scope:xviz.v2.Polyline)
  })
_sym_db.RegisterMessage(Polyline)

Stadium = _reflection.GeneratedProtocolMessageType('Stadium', (_message.Message,), {
  'DESCRIPTOR' : _STADIUM,
  '__module__' : 'xviz.v2.primitives_pb2'
  # @@protoc_insertion_point(class_scope:xviz.v2.Stadium)
  })
_sym_db.RegisterMessage(Stadium)

Text = _reflection.GeneratedProtocolMessageType('Text', (_message.Message,), {
  'DESCRIPTOR' : _TEXT,
  '__module__' : 'xviz.v2.primitives_pb2'
  # @@protoc_insertion_point(class_scope:xviz.v2.Text)
  })
_sym_db.RegisterMessage(Text)


DESCRIPTOR._options = None
_CIRCLE._options = None
_IMAGE._options = None
_POINT._options = None
_POLYGON._options = None
_POLYLINE._options = None
_STADIUM._options = None
_TEXT._options = None
# @@protoc_insertion_point(module_scope)
