# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)

from google.protobuf.internal.enum_type_wrapper import (
    _EnumTypeWrapper as google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    NewType as typing___NewType,
    Optional as typing___Optional,
    Text as typing___Text,
    cast as typing___cast,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

TextAnchorValue = typing___NewType('TextAnchorValue', builtin___int)
type___TextAnchorValue = TextAnchorValue
TextAnchor: _TextAnchor
class _TextAnchor(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[TextAnchorValue]):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    TEXT_ANCHOR_INVALID = typing___cast(TextAnchorValue, 0)
    START = typing___cast(TextAnchorValue, 1)
    MIDDLE = typing___cast(TextAnchorValue, 2)
    END = typing___cast(TextAnchorValue, 3)
TEXT_ANCHOR_INVALID = typing___cast(TextAnchorValue, 0)
START = typing___cast(TextAnchorValue, 1)
MIDDLE = typing___cast(TextAnchorValue, 2)
END = typing___cast(TextAnchorValue, 3)
type___TextAnchor = TextAnchor

TextAlignmentBaselineValue = typing___NewType('TextAlignmentBaselineValue', builtin___int)
type___TextAlignmentBaselineValue = TextAlignmentBaselineValue
TextAlignmentBaseline: _TextAlignmentBaseline
class _TextAlignmentBaseline(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[TextAlignmentBaselineValue]):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    TEXT_ALIGNMENT_BASELINE_INVALID = typing___cast(TextAlignmentBaselineValue, 0)
    TOP = typing___cast(TextAlignmentBaselineValue, 1)
    CENTER = typing___cast(TextAlignmentBaselineValue, 2)
    BOTTOM = typing___cast(TextAlignmentBaselineValue, 3)
TEXT_ALIGNMENT_BASELINE_INVALID = typing___cast(TextAlignmentBaselineValue, 0)
TOP = typing___cast(TextAlignmentBaselineValue, 1)
CENTER = typing___cast(TextAlignmentBaselineValue, 2)
BOTTOM = typing___cast(TextAlignmentBaselineValue, 3)
type___TextAlignmentBaseline = TextAlignmentBaseline

PointColorModeValue = typing___NewType('PointColorModeValue', builtin___int)
type___PointColorModeValue = PointColorModeValue
PointColorMode: _PointColorMode
class _PointColorMode(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[PointColorModeValue]):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    POINT_COLOR_MODE_INVALID = typing___cast(PointColorModeValue, 0)
    ELEVATION = typing___cast(PointColorModeValue, 1)
    DISTANCE_TO_VEHICLE = typing___cast(PointColorModeValue, 2)
POINT_COLOR_MODE_INVALID = typing___cast(PointColorModeValue, 0)
ELEVATION = typing___cast(PointColorModeValue, 1)
DISTANCE_TO_VEHICLE = typing___cast(PointColorModeValue, 2)
type___PointColorMode = PointColorMode

class StyleClass(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    name: typing___Text = ...

    @property
    def style(self) -> type___StyleObjectValue: ...

    def __init__(self,
        *,
        name : typing___Optional[typing___Text] = None,
        style : typing___Optional[type___StyleObjectValue] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"style",b"style"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"name",b"name",u"style",b"style"]) -> None: ...
type___StyleClass = StyleClass

class StyleObjectValue(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    fill_color: builtin___bytes = ...
    stroke_color: builtin___bytes = ...
    stroke_width: builtin___float = ...
    radius: builtin___float = ...
    text_size: builtin___float = ...
    text_rotation: builtin___float = ...
    text_anchor: type___TextAnchorValue = ...
    text_baseline: type___TextAlignmentBaselineValue = ...
    height: builtin___float = ...

    def __init__(self,
        *,
        fill_color : typing___Optional[builtin___bytes] = None,
        stroke_color : typing___Optional[builtin___bytes] = None,
        stroke_width : typing___Optional[builtin___float] = None,
        radius : typing___Optional[builtin___float] = None,
        text_size : typing___Optional[builtin___float] = None,
        text_rotation : typing___Optional[builtin___float] = None,
        text_anchor : typing___Optional[type___TextAnchorValue] = None,
        text_baseline : typing___Optional[type___TextAlignmentBaselineValue] = None,
        height : typing___Optional[builtin___float] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"fill_color",b"fill_color",u"height",b"height",u"radius",b"radius",u"stroke_color",b"stroke_color",u"stroke_width",b"stroke_width",u"text_anchor",b"text_anchor",u"text_baseline",b"text_baseline",u"text_rotation",b"text_rotation",u"text_size",b"text_size"]) -> None: ...
type___StyleObjectValue = StyleObjectValue

class StyleStreamValue(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    fill_color: builtin___bytes = ...
    stroke_color: builtin___bytes = ...
    stroke_width: builtin___float = ...
    radius: builtin___float = ...
    text_size: builtin___float = ...
    text_rotation: builtin___float = ...
    text_anchor: type___TextAnchorValue = ...
    text_baseline: type___TextAlignmentBaselineValue = ...
    height: builtin___float = ...
    radius_min_pixels: builtin___int = ...
    radius_max_pixels: builtin___int = ...
    stroke_width_min_pixels: builtin___int = ...
    stroke_width_max_pixels: builtin___int = ...
    opacity: builtin___float = ...
    stroked: builtin___bool = ...
    filled: builtin___bool = ...
    extruded: builtin___bool = ...
    radius_pixels: builtin___int = ...
    font_weight: builtin___int = ...
    font_family: typing___Text = ...
    point_color_mode: type___PointColorModeValue = ...
    point_color_domain: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___float] = ...

    def __init__(self,
        *,
        fill_color : typing___Optional[builtin___bytes] = None,
        stroke_color : typing___Optional[builtin___bytes] = None,
        stroke_width : typing___Optional[builtin___float] = None,
        radius : typing___Optional[builtin___float] = None,
        text_size : typing___Optional[builtin___float] = None,
        text_rotation : typing___Optional[builtin___float] = None,
        text_anchor : typing___Optional[type___TextAnchorValue] = None,
        text_baseline : typing___Optional[type___TextAlignmentBaselineValue] = None,
        height : typing___Optional[builtin___float] = None,
        radius_min_pixels : typing___Optional[builtin___int] = None,
        radius_max_pixels : typing___Optional[builtin___int] = None,
        stroke_width_min_pixels : typing___Optional[builtin___int] = None,
        stroke_width_max_pixels : typing___Optional[builtin___int] = None,
        opacity : typing___Optional[builtin___float] = None,
        stroked : typing___Optional[builtin___bool] = None,
        filled : typing___Optional[builtin___bool] = None,
        extruded : typing___Optional[builtin___bool] = None,
        radius_pixels : typing___Optional[builtin___int] = None,
        font_weight : typing___Optional[builtin___int] = None,
        font_family : typing___Optional[typing___Text] = None,
        point_color_mode : typing___Optional[type___PointColorModeValue] = None,
        point_color_domain : typing___Optional[typing___Iterable[builtin___float]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"extruded",b"extruded",u"fill_color",b"fill_color",u"filled",b"filled",u"font_family",b"font_family",u"font_weight",b"font_weight",u"height",b"height",u"opacity",b"opacity",u"point_color_domain",b"point_color_domain",u"point_color_mode",b"point_color_mode",u"radius",b"radius",u"radius_max_pixels",b"radius_max_pixels",u"radius_min_pixels",b"radius_min_pixels",u"radius_pixels",b"radius_pixels",u"stroke_color",b"stroke_color",u"stroke_width",b"stroke_width",u"stroke_width_max_pixels",b"stroke_width_max_pixels",u"stroke_width_min_pixels",b"stroke_width_min_pixels",u"stroked",b"stroked",u"text_anchor",b"text_anchor",u"text_baseline",b"text_baseline",u"text_rotation",b"text_rotation",u"text_size",b"text_size"]) -> None: ...
type___StyleStreamValue = StyleStreamValue

class Color(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    values: builtin___bytes = ...

    def __init__(self,
        *,
        values : typing___Optional[builtin___bytes] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"values",b"values"]) -> None: ...
type___Color = Color
