class UI_TYPES:
    CONTAINER = "CONTAINER"
    METRIC = "METRIC"
    PANEL = "PANEL"
    PLOT = "PLOT"
    SELECT = "SELECT"
    TABLE = "TABLE"
    TREETABLE = "TREETABLE"
    VIDEO = "VIDEO"


class UI_LAYOUT:
    HORIZONTAL = "HORIZONTAL"
    VERTICAL = "VERTICAL"


class UI_INTERACTIONS:
    REORDERABLE = "REORDERABLE"
    DRAG_OUT = "DRAG_OUT"
