// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: uiprimitives.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_uiprimitives_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_uiprimitives_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "options.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_uiprimitives_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_uiprimitives_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_uiprimitives_2eproto;
namespace xviz {
class TreeTable;
class TreeTableDefaultTypeInternal;
extern TreeTableDefaultTypeInternal _TreeTable_default_instance_;
class TreeTableColumn;
class TreeTableColumnDefaultTypeInternal;
extern TreeTableColumnDefaultTypeInternal _TreeTableColumn_default_instance_;
class TreeTableNode;
class TreeTableNodeDefaultTypeInternal;
extern TreeTableNodeDefaultTypeInternal _TreeTableNode_default_instance_;
}  // namespace xviz
PROTOBUF_NAMESPACE_OPEN
template<> ::xviz::TreeTable* Arena::CreateMaybeMessage<::xviz::TreeTable>(Arena*);
template<> ::xviz::TreeTableColumn* Arena::CreateMaybeMessage<::xviz::TreeTableColumn>(Arena*);
template<> ::xviz::TreeTableNode* Arena::CreateMaybeMessage<::xviz::TreeTableNode>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace xviz {

enum TreeTableColumn_ColumnType : int {
  TreeTableColumn_ColumnType_TREE_TABLE_COLUMN_COLUMN_TYPE_INVALID = 0,
  TreeTableColumn_ColumnType_INT32 = 1,
  TreeTableColumn_ColumnType_DOUBLE = 2,
  TreeTableColumn_ColumnType_STRING = 3,
  TreeTableColumn_ColumnType_BOOLEAN = 4,
  TreeTableColumn_ColumnType_TreeTableColumn_ColumnType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  TreeTableColumn_ColumnType_TreeTableColumn_ColumnType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool TreeTableColumn_ColumnType_IsValid(int value);
constexpr TreeTableColumn_ColumnType TreeTableColumn_ColumnType_ColumnType_MIN = TreeTableColumn_ColumnType_TREE_TABLE_COLUMN_COLUMN_TYPE_INVALID;
constexpr TreeTableColumn_ColumnType TreeTableColumn_ColumnType_ColumnType_MAX = TreeTableColumn_ColumnType_BOOLEAN;
constexpr int TreeTableColumn_ColumnType_ColumnType_ARRAYSIZE = TreeTableColumn_ColumnType_ColumnType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* TreeTableColumn_ColumnType_descriptor();
template<typename T>
inline const std::string& TreeTableColumn_ColumnType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, TreeTableColumn_ColumnType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function TreeTableColumn_ColumnType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    TreeTableColumn_ColumnType_descriptor(), enum_t_value);
}
inline bool TreeTableColumn_ColumnType_Parse(
    const std::string& name, TreeTableColumn_ColumnType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<TreeTableColumn_ColumnType>(
    TreeTableColumn_ColumnType_descriptor(), name, value);
}
// ===================================================================

class TreeTable :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:xviz.TreeTable) */ {
 public:
  TreeTable();
  virtual ~TreeTable();

  TreeTable(const TreeTable& from);
  TreeTable(TreeTable&& from) noexcept
    : TreeTable() {
    *this = ::std::move(from);
  }

  inline TreeTable& operator=(const TreeTable& from) {
    CopyFrom(from);
    return *this;
  }
  inline TreeTable& operator=(TreeTable&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TreeTable& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TreeTable* internal_default_instance() {
    return reinterpret_cast<const TreeTable*>(
               &_TreeTable_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TreeTable& a, TreeTable& b) {
    a.Swap(&b);
  }
  inline void Swap(TreeTable* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TreeTable* New() const final {
    return CreateMaybeMessage<TreeTable>(nullptr);
  }

  TreeTable* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TreeTable>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TreeTable& from);
  void MergeFrom(const TreeTable& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TreeTable* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "xviz.TreeTable";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_uiprimitives_2eproto);
    return ::descriptor_table_uiprimitives_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kColumnsFieldNumber = 1,
    kNodesFieldNumber = 2,
  };
  // repeated .xviz.TreeTableColumn columns = 1;
  int columns_size() const;
  private:
  int _internal_columns_size() const;
  public:
  void clear_columns();
  ::xviz::TreeTableColumn* mutable_columns(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::xviz::TreeTableColumn >*
      mutable_columns();
  private:
  const ::xviz::TreeTableColumn& _internal_columns(int index) const;
  ::xviz::TreeTableColumn* _internal_add_columns();
  public:
  const ::xviz::TreeTableColumn& columns(int index) const;
  ::xviz::TreeTableColumn* add_columns();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::xviz::TreeTableColumn >&
      columns() const;

  // repeated .xviz.TreeTableNode nodes = 2;
  int nodes_size() const;
  private:
  int _internal_nodes_size() const;
  public:
  void clear_nodes();
  ::xviz::TreeTableNode* mutable_nodes(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::xviz::TreeTableNode >*
      mutable_nodes();
  private:
  const ::xviz::TreeTableNode& _internal_nodes(int index) const;
  ::xviz::TreeTableNode* _internal_add_nodes();
  public:
  const ::xviz::TreeTableNode& nodes(int index) const;
  ::xviz::TreeTableNode* add_nodes();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::xviz::TreeTableNode >&
      nodes() const;

  // @@protoc_insertion_point(class_scope:xviz.TreeTable)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::xviz::TreeTableColumn > columns_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::xviz::TreeTableNode > nodes_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_uiprimitives_2eproto;
};
// -------------------------------------------------------------------

class TreeTableColumn :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:xviz.TreeTableColumn) */ {
 public:
  TreeTableColumn();
  virtual ~TreeTableColumn();

  TreeTableColumn(const TreeTableColumn& from);
  TreeTableColumn(TreeTableColumn&& from) noexcept
    : TreeTableColumn() {
    *this = ::std::move(from);
  }

  inline TreeTableColumn& operator=(const TreeTableColumn& from) {
    CopyFrom(from);
    return *this;
  }
  inline TreeTableColumn& operator=(TreeTableColumn&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TreeTableColumn& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TreeTableColumn* internal_default_instance() {
    return reinterpret_cast<const TreeTableColumn*>(
               &_TreeTableColumn_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(TreeTableColumn& a, TreeTableColumn& b) {
    a.Swap(&b);
  }
  inline void Swap(TreeTableColumn* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TreeTableColumn* New() const final {
    return CreateMaybeMessage<TreeTableColumn>(nullptr);
  }

  TreeTableColumn* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TreeTableColumn>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TreeTableColumn& from);
  void MergeFrom(const TreeTableColumn& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TreeTableColumn* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "xviz.TreeTableColumn";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_uiprimitives_2eproto);
    return ::descriptor_table_uiprimitives_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef TreeTableColumn_ColumnType ColumnType;
  static constexpr ColumnType TREE_TABLE_COLUMN_COLUMN_TYPE_INVALID =
    TreeTableColumn_ColumnType_TREE_TABLE_COLUMN_COLUMN_TYPE_INVALID;
  static constexpr ColumnType INT32 =
    TreeTableColumn_ColumnType_INT32;
  static constexpr ColumnType DOUBLE =
    TreeTableColumn_ColumnType_DOUBLE;
  static constexpr ColumnType STRING =
    TreeTableColumn_ColumnType_STRING;
  static constexpr ColumnType BOOLEAN =
    TreeTableColumn_ColumnType_BOOLEAN;
  static inline bool ColumnType_IsValid(int value) {
    return TreeTableColumn_ColumnType_IsValid(value);
  }
  static constexpr ColumnType ColumnType_MIN =
    TreeTableColumn_ColumnType_ColumnType_MIN;
  static constexpr ColumnType ColumnType_MAX =
    TreeTableColumn_ColumnType_ColumnType_MAX;
  static constexpr int ColumnType_ARRAYSIZE =
    TreeTableColumn_ColumnType_ColumnType_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  ColumnType_descriptor() {
    return TreeTableColumn_ColumnType_descriptor();
  }
  template<typename T>
  static inline const std::string& ColumnType_Name(T enum_t_value) {
    static_assert(::std::is_same<T, ColumnType>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function ColumnType_Name.");
    return TreeTableColumn_ColumnType_Name(enum_t_value);
  }
  static inline bool ColumnType_Parse(const std::string& name,
      ColumnType* value) {
    return TreeTableColumn_ColumnType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kDisplayTextFieldNumber = 1,
    kUnitFieldNumber = 3,
    kTypeFieldNumber = 2,
  };
  // string display_text = 1;
  void clear_display_text();
  const std::string& display_text() const;
  void set_display_text(const std::string& value);
  void set_display_text(std::string&& value);
  void set_display_text(const char* value);
  void set_display_text(const char* value, size_t size);
  std::string* mutable_display_text();
  std::string* release_display_text();
  void set_allocated_display_text(std::string* display_text);
  private:
  const std::string& _internal_display_text() const;
  void _internal_set_display_text(const std::string& value);
  std::string* _internal_mutable_display_text();
  public:

  // string unit = 3;
  void clear_unit();
  const std::string& unit() const;
  void set_unit(const std::string& value);
  void set_unit(std::string&& value);
  void set_unit(const char* value);
  void set_unit(const char* value, size_t size);
  std::string* mutable_unit();
  std::string* release_unit();
  void set_allocated_unit(std::string* unit);
  private:
  const std::string& _internal_unit() const;
  void _internal_set_unit(const std::string& value);
  std::string* _internal_mutable_unit();
  public:

  // .xviz.TreeTableColumn.ColumnType type = 2;
  void clear_type();
  ::xviz::TreeTableColumn_ColumnType type() const;
  void set_type(::xviz::TreeTableColumn_ColumnType value);
  private:
  ::xviz::TreeTableColumn_ColumnType _internal_type() const;
  void _internal_set_type(::xviz::TreeTableColumn_ColumnType value);
  public:

  // @@protoc_insertion_point(class_scope:xviz.TreeTableColumn)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr display_text_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr unit_;
  int type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_uiprimitives_2eproto;
};
// -------------------------------------------------------------------

class TreeTableNode :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:xviz.TreeTableNode) */ {
 public:
  TreeTableNode();
  virtual ~TreeTableNode();

  TreeTableNode(const TreeTableNode& from);
  TreeTableNode(TreeTableNode&& from) noexcept
    : TreeTableNode() {
    *this = ::std::move(from);
  }

  inline TreeTableNode& operator=(const TreeTableNode& from) {
    CopyFrom(from);
    return *this;
  }
  inline TreeTableNode& operator=(TreeTableNode&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TreeTableNode& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TreeTableNode* internal_default_instance() {
    return reinterpret_cast<const TreeTableNode*>(
               &_TreeTableNode_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(TreeTableNode& a, TreeTableNode& b) {
    a.Swap(&b);
  }
  inline void Swap(TreeTableNode* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TreeTableNode* New() const final {
    return CreateMaybeMessage<TreeTableNode>(nullptr);
  }

  TreeTableNode* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TreeTableNode>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TreeTableNode& from);
  void MergeFrom(const TreeTableNode& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TreeTableNode* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "xviz.TreeTableNode";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_uiprimitives_2eproto);
    return ::descriptor_table_uiprimitives_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kColumnValuesFieldNumber = 3,
    kIdFieldNumber = 1,
    kParentFieldNumber = 2,
  };
  // repeated string column_values = 3;
  int column_values_size() const;
  private:
  int _internal_column_values_size() const;
  public:
  void clear_column_values();
  const std::string& column_values(int index) const;
  std::string* mutable_column_values(int index);
  void set_column_values(int index, const std::string& value);
  void set_column_values(int index, std::string&& value);
  void set_column_values(int index, const char* value);
  void set_column_values(int index, const char* value, size_t size);
  std::string* add_column_values();
  void add_column_values(const std::string& value);
  void add_column_values(std::string&& value);
  void add_column_values(const char* value);
  void add_column_values(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& column_values() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_column_values();
  private:
  const std::string& _internal_column_values(int index) const;
  std::string* _internal_add_column_values();
  public:

  // int32 id = 1;
  void clear_id();
  ::PROTOBUF_NAMESPACE_ID::int32 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_id() const;
  void _internal_set_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 parent = 2;
  void clear_parent();
  ::PROTOBUF_NAMESPACE_ID::int32 parent() const;
  void set_parent(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_parent() const;
  void _internal_set_parent(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:xviz.TreeTableNode)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> column_values_;
  ::PROTOBUF_NAMESPACE_ID::int32 id_;
  ::PROTOBUF_NAMESPACE_ID::int32 parent_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_uiprimitives_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TreeTable

// repeated .xviz.TreeTableColumn columns = 1;
inline int TreeTable::_internal_columns_size() const {
  return columns_.size();
}
inline int TreeTable::columns_size() const {
  return _internal_columns_size();
}
inline void TreeTable::clear_columns() {
  columns_.Clear();
}
inline ::xviz::TreeTableColumn* TreeTable::mutable_columns(int index) {
  // @@protoc_insertion_point(field_mutable:xviz.TreeTable.columns)
  return columns_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::xviz::TreeTableColumn >*
TreeTable::mutable_columns() {
  // @@protoc_insertion_point(field_mutable_list:xviz.TreeTable.columns)
  return &columns_;
}
inline const ::xviz::TreeTableColumn& TreeTable::_internal_columns(int index) const {
  return columns_.Get(index);
}
inline const ::xviz::TreeTableColumn& TreeTable::columns(int index) const {
  // @@protoc_insertion_point(field_get:xviz.TreeTable.columns)
  return _internal_columns(index);
}
inline ::xviz::TreeTableColumn* TreeTable::_internal_add_columns() {
  return columns_.Add();
}
inline ::xviz::TreeTableColumn* TreeTable::add_columns() {
  // @@protoc_insertion_point(field_add:xviz.TreeTable.columns)
  return _internal_add_columns();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::xviz::TreeTableColumn >&
TreeTable::columns() const {
  // @@protoc_insertion_point(field_list:xviz.TreeTable.columns)
  return columns_;
}

// repeated .xviz.TreeTableNode nodes = 2;
inline int TreeTable::_internal_nodes_size() const {
  return nodes_.size();
}
inline int TreeTable::nodes_size() const {
  return _internal_nodes_size();
}
inline void TreeTable::clear_nodes() {
  nodes_.Clear();
}
inline ::xviz::TreeTableNode* TreeTable::mutable_nodes(int index) {
  // @@protoc_insertion_point(field_mutable:xviz.TreeTable.nodes)
  return nodes_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::xviz::TreeTableNode >*
TreeTable::mutable_nodes() {
  // @@protoc_insertion_point(field_mutable_list:xviz.TreeTable.nodes)
  return &nodes_;
}
inline const ::xviz::TreeTableNode& TreeTable::_internal_nodes(int index) const {
  return nodes_.Get(index);
}
inline const ::xviz::TreeTableNode& TreeTable::nodes(int index) const {
  // @@protoc_insertion_point(field_get:xviz.TreeTable.nodes)
  return _internal_nodes(index);
}
inline ::xviz::TreeTableNode* TreeTable::_internal_add_nodes() {
  return nodes_.Add();
}
inline ::xviz::TreeTableNode* TreeTable::add_nodes() {
  // @@protoc_insertion_point(field_add:xviz.TreeTable.nodes)
  return _internal_add_nodes();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::xviz::TreeTableNode >&
TreeTable::nodes() const {
  // @@protoc_insertion_point(field_list:xviz.TreeTable.nodes)
  return nodes_;
}

// -------------------------------------------------------------------

// TreeTableColumn

// string display_text = 1;
inline void TreeTableColumn::clear_display_text() {
  display_text_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& TreeTableColumn::display_text() const {
  // @@protoc_insertion_point(field_get:xviz.TreeTableColumn.display_text)
  return _internal_display_text();
}
inline void TreeTableColumn::set_display_text(const std::string& value) {
  _internal_set_display_text(value);
  // @@protoc_insertion_point(field_set:xviz.TreeTableColumn.display_text)
}
inline std::string* TreeTableColumn::mutable_display_text() {
  // @@protoc_insertion_point(field_mutable:xviz.TreeTableColumn.display_text)
  return _internal_mutable_display_text();
}
inline const std::string& TreeTableColumn::_internal_display_text() const {
  return display_text_.GetNoArena();
}
inline void TreeTableColumn::_internal_set_display_text(const std::string& value) {
  
  display_text_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void TreeTableColumn::set_display_text(std::string&& value) {
  
  display_text_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:xviz.TreeTableColumn.display_text)
}
inline void TreeTableColumn::set_display_text(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  display_text_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:xviz.TreeTableColumn.display_text)
}
inline void TreeTableColumn::set_display_text(const char* value, size_t size) {
  
  display_text_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:xviz.TreeTableColumn.display_text)
}
inline std::string* TreeTableColumn::_internal_mutable_display_text() {
  
  return display_text_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* TreeTableColumn::release_display_text() {
  // @@protoc_insertion_point(field_release:xviz.TreeTableColumn.display_text)
  
  return display_text_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void TreeTableColumn::set_allocated_display_text(std::string* display_text) {
  if (display_text != nullptr) {
    
  } else {
    
  }
  display_text_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), display_text);
  // @@protoc_insertion_point(field_set_allocated:xviz.TreeTableColumn.display_text)
}

// .xviz.TreeTableColumn.ColumnType type = 2;
inline void TreeTableColumn::clear_type() {
  type_ = 0;
}
inline ::xviz::TreeTableColumn_ColumnType TreeTableColumn::_internal_type() const {
  return static_cast< ::xviz::TreeTableColumn_ColumnType >(type_);
}
inline ::xviz::TreeTableColumn_ColumnType TreeTableColumn::type() const {
  // @@protoc_insertion_point(field_get:xviz.TreeTableColumn.type)
  return _internal_type();
}
inline void TreeTableColumn::_internal_set_type(::xviz::TreeTableColumn_ColumnType value) {
  
  type_ = value;
}
inline void TreeTableColumn::set_type(::xviz::TreeTableColumn_ColumnType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:xviz.TreeTableColumn.type)
}

// string unit = 3;
inline void TreeTableColumn::clear_unit() {
  unit_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& TreeTableColumn::unit() const {
  // @@protoc_insertion_point(field_get:xviz.TreeTableColumn.unit)
  return _internal_unit();
}
inline void TreeTableColumn::set_unit(const std::string& value) {
  _internal_set_unit(value);
  // @@protoc_insertion_point(field_set:xviz.TreeTableColumn.unit)
}
inline std::string* TreeTableColumn::mutable_unit() {
  // @@protoc_insertion_point(field_mutable:xviz.TreeTableColumn.unit)
  return _internal_mutable_unit();
}
inline const std::string& TreeTableColumn::_internal_unit() const {
  return unit_.GetNoArena();
}
inline void TreeTableColumn::_internal_set_unit(const std::string& value) {
  
  unit_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void TreeTableColumn::set_unit(std::string&& value) {
  
  unit_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:xviz.TreeTableColumn.unit)
}
inline void TreeTableColumn::set_unit(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  unit_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:xviz.TreeTableColumn.unit)
}
inline void TreeTableColumn::set_unit(const char* value, size_t size) {
  
  unit_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:xviz.TreeTableColumn.unit)
}
inline std::string* TreeTableColumn::_internal_mutable_unit() {
  
  return unit_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* TreeTableColumn::release_unit() {
  // @@protoc_insertion_point(field_release:xviz.TreeTableColumn.unit)
  
  return unit_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void TreeTableColumn::set_allocated_unit(std::string* unit) {
  if (unit != nullptr) {
    
  } else {
    
  }
  unit_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), unit);
  // @@protoc_insertion_point(field_set_allocated:xviz.TreeTableColumn.unit)
}

// -------------------------------------------------------------------

// TreeTableNode

// int32 id = 1;
inline void TreeTableNode::clear_id() {
  id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TreeTableNode::_internal_id() const {
  return id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TreeTableNode::id() const {
  // @@protoc_insertion_point(field_get:xviz.TreeTableNode.id)
  return _internal_id();
}
inline void TreeTableNode::_internal_set_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  id_ = value;
}
inline void TreeTableNode::set_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:xviz.TreeTableNode.id)
}

// int32 parent = 2;
inline void TreeTableNode::clear_parent() {
  parent_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TreeTableNode::_internal_parent() const {
  return parent_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TreeTableNode::parent() const {
  // @@protoc_insertion_point(field_get:xviz.TreeTableNode.parent)
  return _internal_parent();
}
inline void TreeTableNode::_internal_set_parent(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  parent_ = value;
}
inline void TreeTableNode::set_parent(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_parent(value);
  // @@protoc_insertion_point(field_set:xviz.TreeTableNode.parent)
}

// repeated string column_values = 3;
inline int TreeTableNode::_internal_column_values_size() const {
  return column_values_.size();
}
inline int TreeTableNode::column_values_size() const {
  return _internal_column_values_size();
}
inline void TreeTableNode::clear_column_values() {
  column_values_.Clear();
}
inline std::string* TreeTableNode::add_column_values() {
  // @@protoc_insertion_point(field_add_mutable:xviz.TreeTableNode.column_values)
  return _internal_add_column_values();
}
inline const std::string& TreeTableNode::_internal_column_values(int index) const {
  return column_values_.Get(index);
}
inline const std::string& TreeTableNode::column_values(int index) const {
  // @@protoc_insertion_point(field_get:xviz.TreeTableNode.column_values)
  return _internal_column_values(index);
}
inline std::string* TreeTableNode::mutable_column_values(int index) {
  // @@protoc_insertion_point(field_mutable:xviz.TreeTableNode.column_values)
  return column_values_.Mutable(index);
}
inline void TreeTableNode::set_column_values(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:xviz.TreeTableNode.column_values)
  column_values_.Mutable(index)->assign(value);
}
inline void TreeTableNode::set_column_values(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:xviz.TreeTableNode.column_values)
  column_values_.Mutable(index)->assign(std::move(value));
}
inline void TreeTableNode::set_column_values(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  column_values_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:xviz.TreeTableNode.column_values)
}
inline void TreeTableNode::set_column_values(int index, const char* value, size_t size) {
  column_values_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:xviz.TreeTableNode.column_values)
}
inline std::string* TreeTableNode::_internal_add_column_values() {
  return column_values_.Add();
}
inline void TreeTableNode::add_column_values(const std::string& value) {
  column_values_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:xviz.TreeTableNode.column_values)
}
inline void TreeTableNode::add_column_values(std::string&& value) {
  column_values_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:xviz.TreeTableNode.column_values)
}
inline void TreeTableNode::add_column_values(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  column_values_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:xviz.TreeTableNode.column_values)
}
inline void TreeTableNode::add_column_values(const char* value, size_t size) {
  column_values_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:xviz.TreeTableNode.column_values)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
TreeTableNode::column_values() const {
  // @@protoc_insertion_point(field_list:xviz.TreeTableNode.column_values)
  return column_values_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
TreeTableNode::mutable_column_values() {
  // @@protoc_insertion_point(field_mutable_list:xviz.TreeTableNode.column_values)
  return &column_values_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace xviz

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::xviz::TreeTableColumn_ColumnType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::xviz::TreeTableColumn_ColumnType>() {
  return ::xviz::TreeTableColumn_ColumnType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_uiprimitives_2eproto
