# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xviz/v2/options.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='xviz/v2/options.proto',
  package='xviz.v2',
  syntax='proto3',
  serialized_options=_b('\n\013com.xviz.v2B\014OptionsProtoP\001Z\004v2pb\242\002\004XVIZ\252\002\007xviz.V2\312\002\007Xviz\\V2'),
  serialized_pb=_b('\n\x15xviz/v2/options.proto\x12\x07xviz.v2\x1a google/protobuf/descriptor.proto:;\n\x10xviz_json_schema\x12\x1f.google.protobuf.MessageOptions\x18\xb8\xa7\x03 \x01(\tB>\n\x0b\x63om.xviz.v2B\x0cOptionsProtoP\x01Z\x04v2pb\xa2\x02\x04XVIZ\xaa\x02\x07xviz.V2\xca\x02\x07Xviz\\V2b\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])


XVIZ_JSON_SCHEMA_FIELD_NUMBER = 54200
xviz_json_schema = _descriptor.FieldDescriptor(
  name='xviz_json_schema', full_name='xviz.v2.xviz_json_schema', index=0,
  number=54200, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=_b("").decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)

DESCRIPTOR.extensions_by_name['xviz_json_schema'] = xviz_json_schema
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(xviz_json_schema)

DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
